perri_default_channel:
- type: "telegram"
  bot_api_token: ""
  chat_id: ""
  display_tags: true
  merge_duplicate_message: true
- type: "slack"
  incoming_webhook_url: ""
  display_tags: true
  merge_duplicate_message: true
- type: "webhook"
  webhook_url: ""
  display_tags: true
  merge_duplicate_message: true
